### ISSUE TITLE
Download issues via Twitch/Curseforge

### ISSUE THREAD

**Issue by tflo** [johnkoerner/AdiBagsTSMPriceGroup#1]
Installation via Twitch client doesn’t work at all (at least on the Mac).

When I manually download the Zip from Curseforge, I see the likely reason for this:

- The files have their parent path prefixed in the file name (see screenshot below)
- Faulty folder name

![Screen Shot 2020-05-10 at 12 20 05-pty-fs8](https://user-images.githubusercontent.com/1410282/81496566-d3024300-92b8-11ea-8671-adaaccf61ece.png)

Downloaded from Github it works fine. (File and folder names are correct in the Github Zip.)

**Comment by johnkoerner** [comment]
I published a new version to Twitch that should fix this.  I labeled it version 1.2.

**Comment by tflo** [comment]
It installs fine now. Thanks!
