### ISSUE TITLE
Price groups for Battle Pets?

### ISSUE THREAD

**Issue by tflo** [johnkoerner/AdiBagsTSMPriceGroup#2]
Is there a way to make the addon work with Battle Pets? (The TSM sources are there, in the TSM tooltip, but the addon doesn’t group accordingly.)

Works only with Battle Pets that are still in their “recipe” form (“teaches you to summon <petname>”).

**Comment by johnkoerner** [comment]
I did a bit of digging on this one. It will require some more research though. The code I get back from AdiBags just tells me that it is a `Pet Cage`, so I need to figure out the correct call to get back the type of pet from that.

**Comment by tflo** [comment]
Thanks for the feedback and the efforts. Highly appreciated!

**Comment by johnkoerner** [comment]
Sorry for the delay on this one. I left the game for a bit. Now that I am back for Dragonflight, I fixed this.  Try it out and let me know what you think,
